# -*- coding: utf-8 -*-
"""Cleaned_NumPy_CSVFile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTiAOqRoDBYyye2yzPKWeaqiIheAtqvA
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()
df = pd.read_csv('Maternal_Mortality_Timing - Sheet1.csv')

print("\nDataFrame summary:")
print(df.info())

total_mortality = df['Total'].values

mean_mortality = np.nanmean(total_mortality)
total_mortality = np.where(np.isnan(total_mortality), mean_mortality, total_mortality)

valid_mortality_count = total_mortality[(total_mortality >= 0) & (total_mortality <= 100)]
df = df[df['Total'].isin(valid_mortality_count)]

during_pregnancy = df['During pregnancy'].values
avg_during = np.mean(during_pregnancy)
max_during = np.max(during_pregnancy)

min_total = np.min(Total)
max_total = np.max(Total)
normalized_total = (Total - min_total) / (max_total - min_total)
df['Normalized_Total'] = normalized_total