# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlZL8SIBFvpp-GUs6AulBxoTZWwJCU1b
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

#load dataset
mortality_df = pd.read_csv("mortality_data.csv")

# Histogram of superhero heights
plt.figure(figsize=(8,5))
sns.histplot(mortality_df['During pregnancy'], bins=20, kde=True)
plt.title('Distribution of mortality during pregnancy')
plt.xlabel('deaths')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(y=mortality_df ["During pregnancy"], color="red")
plt.title("Boxplot of mortality during pregnancy (Outlier Detection)")
plt.ylabel("During pregnancy")
plt.show()

# Check summary statistics of BMI
bmi_summary = mortality_df["During pregnancy"].describe()
bmi_summary

# Scatter plot: During pregnancy vs 0 to 60 days postpartum
plt.figure(figsize=(8,5))
sns.scatterplot(x=mortality_df['During pregnancy'], y=mortality_df['0 to 60 days '])
plt.title("Moartality During pregnancy vs. 0 to 60 days postpartum")
plt.xlabel("During pregnancy")
plt.ylabel("0 to 60 days postpartum")
plt.show()