# -*- coding: utf-8 -*-
"""Normalization_Tranformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXAmTtv_-wZ_QbpfLBBsewJXRKCgWiST
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Sample data
data = pd.DataFrame({
    'Total': [73, 39, 8, 9, 28, 60, 41, 74, 28, 27, 24, 105],
    'During_pregnancy': [19, 9, 2, 0, 11, 12, 7, 21, 5, 4, 6, 24],
    'zero_to_sixty_days': [32, 21, 3, 7, 12, 29, 22, 31, 12, 20, 9, 54]
})
scaler = MinMaxScaler()
data[['Total', 'During_pregnancy']] = scaler.fit_transform(data[['Total', 'During_pregnancy']])
data['zero_to_sixty_days'] = np.log1p(data['zero_to_sixty_days'])
print(data)